stages:
  - build
  - test
  - deploy

image: node:14.8.1

# pre-job:
#   stage: .pre
#   script:
#     - apt-get update -qq && apt-get install -y nodejs npm
#     - node -v

build-job:
  stage: build
  script:
    - npm install
    - npm run build
  # This folder is cached between builds
  # https://docs.gitlab.com/ee/ci/yaml/index.html#cache
  cache:
    paths:
      - node_modules/

job-test:
  stage: test
  script:
    - curl -f https://get.pnpm.io/v6.16.js | node - add --global pnpm
    - pnpm -v
