base: /blog/
title: 十年磨一剑
head:
  - link
  - { rel: icon, href: /logo.png }
description: "JavaScript学习地，前端进阶之路"
locales:
  # 键名是该语言所属的子路径
  # 作为特例，默认语言可以使用 '/' 作为其路径。
  /:
    lang: "en-US" # 将会被设置为 <html> 的 lang 属性
    title: "Grinding sword"
    description: "Vue-powered Static Site Generator"

  /zh/:
    lang: "zh-CN"
    title: "磨刀"
    description: "Vue 驱动的静态网站生成器"

themeConfig:
  # logo: /assets/img/logo.png
  locales:
    /:
      lang: "en-US" # 将会被设置为 <html> 的 lang 属性
      title: "磨剑"
      description: "Vue-powered Static Site Generator"
      nav:
        - { text: Home, link: / }
        - { text: Guide, link: /guide/, target: _self }
        - { text: External, link: https://google.com, target: _blank, rel: "" }
    /zh/:
      lang: "zh-CN"
      title: "磨刀"
      selectText: "选择语言"
      label: "简体中文"
      description: "Vue 驱动的静态网站生成器"
      nav:
        - { text: 主页, link: /zh/ }
        - { text: 指南, link: /zh/guide/, target: _self }
        - { text: 外部, link: https://google.com, target: _blank, rel: "" }
      sidebar:
        - /zh/
        - [/zh/html/, HTML]
        - [/zh/css/, CSS]
        - [/zh/javascript/, JavaScript]
        - title: 工具利器 # 必要的
          path: /zh/tools/ # 可选的, 应该是一个绝对路径
          # collapsable: false # 可选的, 默认值是 true,
          sidebarDepth: 1 # 可选的, 默认值是 1
          children:
            - [/zh/tools/efficient, 效率工具]
            - [/zh/tools/site, 有趣的网站]
      displayAllHeaders: true # 显示所有页面的标题链接
      lastUpdated: "Last Updated" # string | boolean
