base: /blog/
title: 十年磨一剑
head:
  - - link
    - { rel: icon, href: /logo.png }
description: "JavaScript学习地，前端进阶之路"

locales:
  /:
    lang: 'en-US' # 将会被设置为 <html> 的 lang 属性
    title: '磨剑'
    description: 'Vue-powered Static Site Generator'
  /zh/:
    lang: "zh-CN"
    title: "磨刀"
    selectText: '选择语言'
    label: '简体中文'
    description: "Vue 驱动的静态网站生成器"
    themeConfig:
    # logo: /assets/img/logo.png
    nav:
      - { text: Home, link: /zh/home/ }
      - { text: Guide, link: /zh/guide/, target: _self }
      - { text: External, link: https://google.com, target: _blank, rel: "" }
    # sidebar:
    #   - {/zh/css/: [one, two]}
    #   - {/zh/html/: [one, two]}
    displayAllHeaders: true
